export const BREAKPOINT_RESPONSIVE_SM = 640;
export const BREAKPOINT_RESPONSIVE_MD = 768;
export const BREAKPOINT_RESPONSIVE_LG = 1024;
export const BREAKPOINT_RESPONSIVE_XL = 1280;
export const BREAKPOINT_RESPONSIVE_2XL = 1536;
